#!/bin/bash
export MIX_ENV=prod
mix phx.digest
mix release --env=prod

v=$(ls -v _build/prod/rel/microblog/releases/ | grep -e "[0-9].[0-9].[0-9]" | tail -n 1)
echo $v
echo _build/prod/rel/microblog/releases/$v/microblog.tar.gz

scp _build/prod/rel/microblog/releases/$v/microblog.tar.gz microblog@devonherlitz.solutions:/home/microblog/

echo "deployed as tar on server"